# Workflow name
name: Build and Publish Project and Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Install dependencies
      - run: npm install

      # Build the React project (Vite)
      - run: npm run build
        env:
          CI: true

      # Move the built project to the GitHub Pages root (./gh-pages/)
      - run: |
          mkdir -p ./gh-pages
          mv ./dist/* ./gh-pages/

      # Build Storybook
      - run: npm run build-storybook

      # Move the Storybook build to the 'storybook' subdirectory in GitHub Pages
      - run: |
          mkdir -p ./gh-pages/storybook
          mv ./storybook-static/* ./gh-pages/storybook/

      # Deploy the combined result to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
