# Workflow name
name: Build and Publish Project and Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Install dependencies
      - run: npm install

      # Build the React project (Vite)
      - run: npm run build
        env:
          CI: true

      # Move the built project to a directory for GitHub Pages
      - run: |
          mkdir -p ./gh-pages/project
          mv ./dist/* ./gh-pages/project/

      # Build Storybook
      - run: npm run build-storybook

      # Move Storybook to the 'storybook' directory
      - run: |
          mkdir -p ./gh-pages/storybook
          mv ./storybook-static/* ./gh-pages/storybook/

      # Upload to GitHub Pages artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./gh-pages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
